// Generated by Haxe 5.0.0-preview.1;
// TypeScript Target;
;
const $hxClasses: any = {};
const $global: any = typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this;
var __map_reserved: any = {};
;
export class Std {
public static $string(s: any): string {
		return js.Boot.__string_rec(s,"");
	}
	}
export class TestDoWhile {
private static main(): void {
		let i = 0;
		do {
			{
				haxe.Log.trace(i,{ fileName: "TestDoWhile.hx", lineNumber: 5, className: "TestDoWhile", methodName: "main" });
				++i;
			}
		} while ((i < 5));
		let j = 0;
		do {
			++j;
		} while ((j < 3));
	}
	}
export namespace haxe {
export class Log {
	public static formatOutput(v: any /* circular */, infos: { className: any /* circular */; customParams: any /* circular */[]; fileName: any /* circular */; lineNumber: number; methodName: any /* circular */; }): any /* circular */ {
			let str = Std.$string(v);
			if ((infos == null)) {
				return str;
			}
			let pstr = infos.fileName + ":" + infos.lineNumber;
			if ((infos.customParams != null)) {
				let _g = 0;
				let _g1 = infos.customParams;
				while ((_g < _g1.length)) {
					let v = _g1[_g];
					++_g;
					str += ", " + Std.$string(v);
				}
			}
			return pstr + ": " + str;
		}
		public static trace(v: any /* circular */, infos: { className: any /* circular */; customParams: any /* circular */; fileName: any /* circular */; lineNumber: any /* circular */; methodName: any /* circular */; }): void {
			let str = haxe.Log.formatOutput(v,infos);
			if ((typeof console != "undefined" && console.log != null)) {
				console.log(str);
			}
		}
		}
	}
export namespace haxe {
export namespace iterators {
	export class ArrayIterator<T> {
		private array: T[];
			private current: any /* circular */;
			constructor(array: any /* circular */) {
				this.current = 0;
				this.array = array;
			}
			public hasNext(): boolean {
				return this.current < this.array.length;
			}
			public next(): T {
				return this.array[this.current++];
			}
			}
		}
	}
export namespace js {
export class Boot {
	private static __toStr: Function;
		private static __string_rec(o: { __enum__: any /* circular */; __params__: any /* circular */; _hx_index: number; hasOwnProperty: (arg1: any /* circular */) => any /* circular */; length: any /* circular */; toString: () => string; }, s: any /* circular */): any /* circular */ {
			if ((o == null)) {
				return "null";
			}
			if ((s.length >= 5)) {
				return "<...>";
			}
			let t = typeof o;
			if ((t == "function" && (o.__name__ || o.__ename__))) {
				t = "object";
			}
			switch ((t)) {
			case "function":
			return "<function>";
				break;
			case "object":
			{
					;
					if ((o instanceof Array)) {
						let str = "[";
						s += "\t";
						{
							let _g = 0;
							let _g1 = o.length;
							while ((_g < _g1)) {
								let i = _g++;
								str += ((i > 0) ? "," : "") + js.Boot.__string_rec(o[i],s);
							}
						}
						str += "]";
						return str;
					}
					let tostr;
					try {
						tostr = o.toString;
					} catch (_g) {
						return "???";
					}
					if ((tostr != null && tostr != Object.toString && typeof tostr == "function")) {
						let s2 = o.toString();
						if ((s2 != "[object Object]")) {
							return s2;
						}
					}
					let str = "{\n";
					s += "\t";
					let hasp = o.hasOwnProperty != null;
					let k = null;
					for( k in o ) {
					if ((hasp && !o.hasOwnProperty(k))) {
						continue;
					}
					if ((k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__")) {
						continue;
					}
					if ((str.length != 2)) {
						str += ", \n";
					}
					str += s + k + " : " + js.Boot.__string_rec(o[k],s);
					}
					s = s.substring(1);
					str += "\n" + s + "}";
					return str;
				}
				break;
			case "string":
			return o;
				break;
			default:
				return String(o);
			}
		}
		}
	}

{
	;
	String.__name__ = "String";
	;
	Array.__name__ = "Array";
	;
	;
	;
	;
	;
	;
	;
}
TestDoWhile.main();
