// Generated by Haxe 5.0.0-preview.1
// TypeScript Declaration File

export class Std {
	public static $string(s: any /* circular */): any /* circular */;
}

export class TestDoWhile {
	private static main(): any /* circular */;
}

export namespace haxe {
export class Log {
	public static formatOutput(v: any /* circular */, infos: any /* circular */): any /* circular */;
	public static trace(v: any /* circular */, infos?: any /* circular */): any /* circular */;
}
}

export namespace haxe {
export namespace iterators {
export class ArrayIterator<T> {
	private array: any /* circular */;
	private current: any /* circular */;
	public hasNext(): any /* circular */;
	public next(): any /* circular */;
}
}
}

export namespace js {
export class Boot {
	private static __string_rec(o: any /* circular */, s: any /* circular */): any /* circular */;
	private static __toStr: any /* circular */;
}
}

