// Generated by Haxe 5.0.0-preview.1
(function ($global) { "use strict";
var TestSimple = function() {
	console.log("TestSimple.hx:3:","Created");
};
TestSimple.main = function() {
	var t = new TestSimple();
	console.log("TestSimple.hx:7:",js_Boot.getClass(t));
};
TestSimple.prototype = {
	__class__: TestSimple
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var js_Boot = function() { };
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
Object.defineProperty(String.prototype,"__class__",{ value : String, enumerable : false, writable : true});
js_Boot.__toStr = ({ }).toString;
TestSimple.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
